#!/bin/bash

init () {
  export cpu_cloc=2GHz
  export cache_line_size=64
  export l1_icache=32kB
  export l1_icache_assoc=2
  export l1_dcache=64kB
  export l1_dcache_assoc=2
  export l2_cache=2MB
  export l2_assoc=8
}

run_all () {
  (./specbzip_run & ./spechmmer_run & ./specmcf_run) ; (./specsjeng_run & ./speclbm_run) ; init ;
}

figlet Call_199

#FIRST RUN
#init
#run_all
#
#export cpu_cloc=1GHz
#
#run_all
#
#export l1_icache=64kB
#export l1_icache_assoc=4
#
#run_all
#
#export l1_dcache=128kB
#export l1_dcache_assoc=4
#
#run_all
#
#export l2_cache=4MB
#export l2_assoc=8
#
#run_all

#SECOND RUN
init
#L1 ichace
export l1_icache=128kB
export l1_icache_assoc=8
run_all
export l1_icache=32kB
export l1_icache_assoc=8
run_all
#L1 dcache
export l1_dcache=128kB
export l1_dcache_assoc=8
run_all
export l1_dcache=32kB
export l1_dcache_assoc=2
run_all
export l1_dcache=128kB
export l1_dcache_assoc=4
run_all
#L2 cache
export l2_cache=1MB
export l2_assoc=2
run_all
export l2_cache=2MB
export l2_assoc=8
run_all
export l2_cache=4MB
export l2_assoc=4
run_all
#cache_line_size
export cache_line_size=32
run_all
export cache_line_size=128
run_all

figlet Done
